/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    jacoco
    id("com.github.kt3k.coveralls") version "2.12.2"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.junit.jupiter:junit-jupiter-engine:5.3.1")
    implementation("org.junit.jupiter:junit-jupiter-params:5.3.1")
    testImplementation("org.junit.platform:junit-platform-runner:1.3.1")
    testImplementation("org.junit.platform:junit-platform-launcher:1.3.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.3.1")
}

group = "org.simplegraph"
version = "1.0.1"
description = "simple single-edge graph implemetation"
configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
                         "Implementation-Version" to project.version))
    }
}

tasks.jacocoTestReport {
    reports {
        xml.required = true
        csv.required = false
        html.required = true
    }
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport) // report is always generated after tests run
}
tasks.jacocoTestReport {
    dependsOn(tasks.test) // tests are required to run before generating the report
}

