/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("net.saliman.cobertura") version "4.0.0"
    id("com.github.kt3k.coveralls") version "2.10.2"
}

apply(plugin = "net.saliman.cobertura")
cobertura.coverageFormats = mutableSetOf("html", "xml")

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.junit.jupiter:junit-jupiter-engine:5.3.1")
    implementation("org.junit.jupiter:junit-jupiter-params:5.3.1")
    testImplementation("org.junit.platform:junit-platform-runner:1.3.1")
    testImplementation("org.junit.platform:junit-platform-launcher:1.3.1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.3.1")
    testRuntime("org.slf4j:slf4j-api:1.7.10")
}

group = "org.simplegraph"
version = "1.0.0"
description = "simplegraph"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
                         "Implementation-Version" to project.version))
    }
}

tasks.test {
    useJUnitPlatform()
}
